import type * as React from "react"

import {
  ArrowDownToLineIcon,
  ArrowLeftIcon,
  BotIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronRightIcon,
  CircleCheckIcon,
  CircleDashedIcon,
  CogIcon,
  CloudDownloadIcon,
  CloudSyncIcon,
  CloudUploadIcon,
  CopyIcon,
  CreditCardIcon,
  EllipsisIcon,
  EyeIcon,
  EyeOffIcon,
  FolderCodeIcon,
  FileUpIcon,
  FolderOpenIcon,
  GaugeIcon,
  HouseIcon,
  ImageIcon,
  LanguagesIcon,
  LoaderCircleIcon,
  MenuIcon,
  MicIcon,
  MoonStarIcon,
  NetworkIcon,
  PackageCheckIcon,
  PackagePlusIcon,
  PackageIcon,
  PencilIcon,
  PlugZapIcon,
  PowerIcon,
  RefreshCwIcon,
  SearchIcon,
  Share2Icon,
  SidebarIcon,
  SlidersHorizontalIcon,
  SparklesIcon,
  SquareArrowOutUpRightIcon,
  SquareTerminalIcon,
  TriangleAlertIcon,
  Trash2Icon,
  UnplugIcon,
  UploadCloudIcon,
  UserRoundIcon,
  VideoIcon,
  BrainCircuitIcon,
  WrenchIcon,
  XIcon,
} from "lucide-react"

export type AppIconComponent = React.ComponentType<React.SVGProps<SVGSVGElement>>

export const AppIcons = {
  action: {
    back: ArrowLeftIcon,
    cancel: XIcon,
    check: CheckIcon,
    checkForUpdates: RefreshCwIcon,
    connect: PlugZapIcon,
    copy: CopyIcon,
    creditCard: CreditCardIcon,
    delete: Trash2Icon,
    disconnect: UnplugIcon,
    download: ArrowDownToLineIcon,
    edit: PencilIcon,
    hideSecret: EyeOffIcon,
    installPackage: PackagePlusIcon,
    menu: MenuIcon,
    more: EllipsisIcon,
    openExternal: SquareArrowOutUpRightIcon,
    openFolder: FolderOpenIcon,
    publish: UploadCloudIcon,
    quit: PowerIcon,
    refresh: RefreshCwIcon,
    settings: SlidersHorizontalIcon,
    share: Share2Icon,
    showSecret: EyeIcon,
    sync: CloudSyncIcon,
    syncFromCloud: CloudDownloadIcon,
    syncToCloud: CloudUploadIcon,
    updatePackage: PackageCheckIcon,
    viewUsage: GaugeIcon,
  },
  capability: {
    audio: MicIcon,
    file: FileUpIcon,
    image: ImageIcon,
    search: SearchIcon,
    video: VideoIcon,
  },
  nav: {
    connections: NetworkIcon,
    home: HouseIcon,
    menu: MenuIcon,
    sidebar: SidebarIcon,
    settings: CogIcon,
    skills: PackageIcon,
  },
  object: {
    account: UserRoundIcon,
    agent: BotIcon,
    connections: NetworkIcon,
    localProject: FolderCodeIcon,
    localSetup: WrenchIcon,
    officialCapability: BrainCircuitIcon,
    skill: PackageIcon,
    terminal: SquareTerminalIcon,
    usage: GaugeIcon,
  },
  preference: {
    language: LanguagesIcon,
    theme: MoonStarIcon,
  },
  status: {
    attention: TriangleAlertIcon,
    check: CheckIcon,
    disclosure: ChevronDownIcon,
    loading: LoaderCircleIcon,
    navigate: ChevronRightIcon,
    pending: CircleDashedIcon,
    ready: CircleCheckIcon,
  },
  utility: {
    search: SearchIcon,
    settings: CogIcon,
    sparkles: SparklesIcon,
  },
} as const
